name: speval
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - altair=2.1.0
  - feather-format=0.4.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_nbextensions_configurator=0.4.0
  - vega=1.3.0
  - vega3=0.13.0
  - vega_datasets=0.5.0
  - geopandas=0.3.0
  - ipywidgets=7.2.1
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.32.1
  - jupyterlab_launcher=0.10.5
  - matplotlib=2.2.2
  - msgpack-python=0.5.6
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.5.0
  - numpy=1.14.5
  - pandas=0.23.1
  - pip=10.0.1
  - python=3.6.5
  - requests=2.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - shapely=1.6.4
  - sqlalchemy=1.2.8
  - sqlite=3.23.1
  - tqdm=4.23.4
  - widgetsnbextension=3.2.1
  - xlrd=1.1.0
  - r-essentials=3.4.3
  - rpy2=2.9.1
  - pip:
    - cython==0.28.2

