remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: "Chicago's Safe Passage Program to Prevent Crime: Is It Worth the Dime?"

markdown: kramdown

author:
  name: Stefan Binder

github_username: binste
linkedin_username: stefan-binder-36b013130